import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '@/lib/theme';

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  taskHeader: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    gap: 2,
  },
  taskGreeting: {
    flexShrink: 1,
    fontSize: 29,
    fontWeight: typography.bold,
    color: colors.text,
    letterSpacing: -0.5,
  },
  taskDateRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  taskDateIts: {
    fontSize: typography.xl,
    fontWeight: typography.bold,
    color: colors.text,
    letterSpacing: -0.5,
    marginRight: 6,
  },
  taskDate: {
    fontSize: typography.xl,
    fontWeight: typography.bold,
    color: '#BEF264',
    letterSpacing: -0.5,
    textShadowColor: 'rgba(190,242,100,0.4)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  taskDateOrdinal: {
    fontSize: 11,
    fontWeight: typography.bold,
    color: '#BEF264',
    marginTop: 3,
  },
  inlineCreatorWrap: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    marginBottom: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  inlineCreatorBar: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  inlineCreatorBarFocused: {
    borderBottomColor: colors.accentCyan,
    backgroundColor: '#00D9FF08',
  },
  inlineCreatorMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  inlineCreatorSearchArea: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  inlineCreatorTitleInput: {
    flex: 1,
    color: colors.text,
    fontSize: 22,
    fontWeight: '500',
  },
  inlineCreatorPlaceholder: {
    flex: 1,
    color: colors.textMuted,
    fontSize: typography.base,
  },
  creatorOverlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.18)',
    zIndex: 39,
  },
  creatorFloatingActions: {
    position: 'absolute',
    zIndex: 41,
    right: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  creatorButtonStack: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  creatorOverlay: {
    position: 'absolute',
    zIndex: 40,
    borderWidth: 1,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  sortTriggerButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  searchIconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    color: colors.text,
    fontSize: typography.sm,
    paddingVertical: 0,
  },
  body: {
    flex: 1,
  },
  taskList: {
    flexGrow: 1,
    paddingTop: spacing.sm,
  },
  placeholder: {
    fontSize: typography.sm,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: spacing.xxl,
  },
  searchResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  searchResultTitle: {
    flex: 1,
    fontSize: typography.base,
    color: colors.text,
  },
  searchResultMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flexShrink: 0,
  },
  sortDropdown: {
    position: 'absolute',
    backgroundColor: '#0b1a38',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: '#20345d',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 14,
    zIndex: 30,
  },
  sortDropdownItem: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  sortDropdownText: {
    flex: 1,
    fontSize: typography.base,
    color: '#d7dce8',
  },
  sheetCreateButton: {
    minWidth: 100,
    height: 40,
    borderRadius: 20,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCreateButtonDisabled: {
    opacity: 0.7,
  },
  sheetCreateButtonText: {
    fontSize: typography.sm,
    color: colors.primaryFg,
    fontWeight: typography.semibold,
  },
  sheetCancelButton: {
    minWidth: 100,
    height: 38,
    borderRadius: 19,
    paddingHorizontal: spacing.md,
    backgroundColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCancelButtonText: {
    fontSize: typography.sm,
    color: '#FFFFFF',
    fontWeight: typography.semibold,
  },
  sheetContent: {
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.md,
    gap: spacing.lg,
    paddingBottom: 160,
  },
  creatorSubtasksCard: {
    gap: 0,
  },
  creatorSubtaskItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 9,
    gap: spacing.sm,
  },
  creatorSubtaskCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: colors.textMuted,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  creatorSubtaskCircleCompleted: {
    borderColor: colors.success,
    backgroundColor: colors.successMuted,
  },
  creatorSubtaskItemTitle: {
    flex: 1,
    fontSize: typography.sm,
    color: colors.text,
  },
  creatorSubtaskItemTitleCompleted: {
    color: colors.textMuted,
    textDecorationLine: 'line-through',
  },
  creatorSubtaskComposerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'transparent',
    gap: spacing.sm,
  },
  creatorSubtaskComposerRowFocused: {
    borderColor: colors.accentCyan,
    backgroundColor: '#00D9FF08',
  },
  creatorSubtaskInput: {
    flex: 1,
    fontSize: typography.sm,
    color: colors.textMuted,
  },
  section: {
    gap: spacing.md,
  },
  sectionTitle: {
    fontSize: typography.sm,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: typography.semibold,
  },
  field: {
    gap: spacing.sm,
  },
  fieldsRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  fieldInRow: {
    flex: 1,
  },
  deadlineField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  deadlineLabelWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  deadlineChipsWrap: {
    flexDirection: 'row',
    gap: spacing.sm,
    flex: 1,
    justifyContent: 'flex-end',
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  fieldLabel: {
    fontSize: typography.sm,
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  parsedDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.warning,
  },
  textInput: {
    height: 50,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBg,
    paddingHorizontal: 14,
    color: colors.text,
    fontSize: typography.base,
  },
  selectButton: {
    height: 50,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBg,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inlineLabeledField: {
    minHeight: 50,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBg,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  inlineFieldLabel: {
    fontSize: typography.base,
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  inlineFieldValueWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.sm,
  },
  inlineFieldValue: {
    fontSize: typography.base,
    color: colors.text,
    textAlign: 'right',
    flexShrink: 1,
  },
  inlineFailureCostValueWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.xs,
  },
  inlineFailureCostInput: {
    minWidth: 56,
    maxWidth: 130,
    fontSize: typography.base,
    color: colors.text,
    textAlign: 'right',
    paddingVertical: 0,
  },
  selectLabel: {
    fontSize: typography.base,
    color: colors.text,
    flex: 1,
    paddingRight: spacing.sm,
  },
  datePicker: {
    alignSelf: 'flex-start',
  },
  reminderCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    backgroundColor: colors.surface2,
    padding: spacing.md,
    gap: spacing.sm,
  },
  reminderHeaderRow: {
    gap: 2,
  },
  reminderEmpty: {
    fontSize: typography.sm,
    color: colors.textMuted,
    paddingVertical: spacing.xs,
  },
  reminderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
    paddingVertical: spacing.xs,
    gap: spacing.sm,
  },
  reminderIndexWrap: {
    width: 36,
    alignItems: 'flex-start',
  },
  reminderIndex: {
    fontSize: typography.sm,
    color: colors.textMuted,
    fontWeight: typography.semibold,
  },
  reminderBody: {
    flex: 1,
    gap: 1,
  },
  reminderAt: {
    fontSize: typography.sm,
    color: colors.text,
    fontWeight: typography.semibold,
  },
  reminderStatus: {
    fontSize: typography.xs,
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  reminderComposer: {
    marginTop: spacing.xs,
    gap: spacing.sm,
  },
  reminderIOSPickers: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reminderChipsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  reminderChip: {
    height: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  reminderChipText: {
    fontSize: typography.sm,
    color: colors.text,
    fontWeight: typography.medium,
  },
  addReminderButton: {
    height: 40,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#FBBF2459',
    backgroundColor: '#FBBF2426',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  addReminderText: {
    fontSize: typography.sm,
    color: '#FBBF24',
    fontWeight: typography.semibold,
  },
  reminderPickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  reminderPickerSheet: {
    position: 'absolute',
    left: spacing.lg,
    right: spacing.lg,
    top: '24%',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    gap: spacing.sm,
  },
  reminderPickerTitle: {
    fontSize: typography.base,
    fontWeight: typography.semibold,
    color: colors.text,
  },
  reminderPickerActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  reminderPickerCancel: {
    flex: 1,
    height: 38,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface2,
  },
  reminderPickerCancelText: {
    fontSize: typography.sm,
    color: colors.textMuted,
    fontWeight: typography.semibold,
  },
  reminderPickerConfirm: {
    flex: 1,
    height: 38,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#FBBF2459',
    backgroundColor: '#FBBF2426',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reminderPickerConfirmText: {
    fontSize: typography.sm,
    color: '#FBBF24',
    fontWeight: typography.semibold,
  },
  recurrenceCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    backgroundColor: colors.surface2,
    padding: spacing.md,
    gap: spacing.sm,
  },
  recurrenceChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  recurrenceChip: {
    minHeight: 30,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  recurrenceChipActive: {
    borderColor: '#C084FC59',
    backgroundColor: '#C084FC1A',
  },
  recurrenceChipText: {
    fontSize: typography.xs,
    color: colors.textMuted,
    fontWeight: typography.semibold,
  },
  recurrenceChipTextActive: {
    color: '#C084FC',
  },
  recurrenceDaysRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginTop: 2,
  },
  recurrenceDayBtn: {
    width: 30,
    height: 30,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recurrenceDayBtnActive: {
    borderColor: '#C084FC66',
    backgroundColor: '#C084FC26',
  },
  recurrenceDayText: {
    fontSize: 11,
    color: colors.textMuted,
    fontWeight: typography.semibold,
  },
  recurrenceDayTextActive: {
    color: '#C084FC',
  },
  placeholderRow: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    backgroundColor: colors.surface2,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  placeholderRowTextWrap: {
    flex: 1,
    gap: spacing.xs,
  },
  placeholderRowTitle: {
    fontSize: typography.base,
    color: colors.text,
    fontWeight: typography.medium,
  },
  placeholderRowSub: {
    fontSize: typography.sm,
    color: colors.textMuted,
    lineHeight: 18,
  },
  // Failure cost
  failureCostRow: {
    flexDirection: 'row',
    height: 50,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBg,
    overflow: 'hidden',
  },
  currencyBadge: {
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: colors.inputBorder,
    backgroundColor: colors.surface2,
  },
  currencySymbol: {
    fontSize: typography.base,
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  currencyIconsWrap: {
    flexDirection: 'row',
    gap: spacing.xs * 0.5,
    alignItems: 'center',
  },
  currencyIconSymbol: {
    fontSize: typography.base,
    color: colors.textMuted,
    fontWeight: typography.bold,
    lineHeight: typography.base * 1.2,
  },
  failureCostInput: {
    flex: 1,
    paddingHorizontal: spacing.md,
    fontSize: typography.base,
    color: colors.text,
  },
  // Voucher dropdown
  selectedFriendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  avatarSmall: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarSmallText: {
    fontSize: typography.xs,
    color: colors.text,
    fontWeight: typography.semibold,
  },
  voucherDropdown: {
    position: 'absolute',
    zIndex: 80,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 30,
    overflow: 'hidden',
  },
  voucherBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  voucherDropdownScroll: {
    maxHeight: 260,
  },
  voucherSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: spacing.sm,
    paddingHorizontal: spacing.sm,
    height: 36,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBg,
    gap: spacing.sm,
  },
  voucherSearchInput: {
    flex: 1,
    fontSize: typography.sm,
    color: colors.text,
    paddingVertical: 0,
  },
  voucherRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  voucherRowSelected: {
    backgroundColor: colors.surface2,
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarSelf: {
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  avatarText: {
    fontSize: typography.sm,
    color: colors.text,
    fontWeight: typography.semibold,
  },
  voucherRowText: {
    flex: 1,
    gap: 1,
  },
  voucherName: {
    flex: 1,
    fontSize: typography.sm,
    color: colors.text,
  },
  voucherSub: {
    fontSize: typography.xs,
    color: colors.textMuted,
  },
  voucherHint: {
    fontSize: typography.sm,
    color: colors.textMuted,
    textAlign: 'center',
    paddingVertical: spacing.lg,
  },

  // Postpone deadline picker modal
  postponeBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  postponeSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl + 8,
    gap: spacing.md,
  },
  postponeTitle: {
    fontSize: typography.base,
    fontWeight: typography.semibold,
    color: colors.text,
  },
  postponeSubtitle: {
    fontSize: typography.sm,
    color: colors.textMuted,
  },
  postponeIosPicker: {
    alignSelf: 'center',
  },
  postponeAndroidRow: {
    gap: spacing.xs,
  },
  postponeActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  postponeCancelBtn: {
    flex: 1,
    paddingVertical: spacing.sm + 2,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  postponeCancelText: {
    fontSize: typography.sm,
    color: colors.textMuted,
  },
  postponeConfirmBtn: {
    flex: 1,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colors.warning,
    alignItems: 'center',
  },
  postponeConfirmText: {
    fontSize: typography.sm,
    fontWeight: typography.semibold,
    color: colors.bg,
  },
});

export { styles };
