const { IOSConfig, withInfoPlist, withPodfile, withXcodeProject } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const APP_INTENTS_PACKAGE_FILE = 'VouchAlarmKitAppIntentsPackage.swift';

function withAlarmKitInfoPlist(config) {
  return withInfoPlist(config, (nextConfig) => {
    delete nextConfig.modResults.NSAlarmKitUsageDescription;
    return nextConfig;
  });
}

function withAlarmKitAppIntentsPackage(config) {
  return withXcodeProject(config, (nextConfig) => {
    const project = nextConfig.modResults;
    const projectRoot = nextConfig.modRequest.projectRoot;
    const projectName = nextConfig.modRequest.projectName;

    if (!projectName) {
      throw new Error('[withAlarmKit] Unable to resolve iOS project name.');
    }

    const sourceRoot = IOSConfig.Paths.getSourceRoot(projectRoot);
    const appIntentsPackagePath = path.join(sourceRoot, APP_INTENTS_PACKAGE_FILE);
    fs.writeFileSync(appIntentsPackagePath, buildAppIntentsPackageSource());

    const projectFilePath = `${projectName}/${APP_INTENTS_PACKAGE_FILE}`;
    if (!project.hasFile(projectFilePath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: projectFilePath,
        groupName: projectName,
        project,
      });
    }

    // Enable AppIntents metadata extraction from dependent static libraries
    const buildConfigs = project.pbxXCBuildConfigurationSection();
    for (const key in buildConfigs) {
      const config = buildConfigs[key];
      if (config.buildSettings && config.buildSettings.PRODUCT_NAME === projectName) {
        config.buildSettings.GENERATE_APPINTENTS_METADATA_FOR_DEPENDENCIES = 'YES';
      }
    }

    return nextConfig;
  });
}

function withMinimumIosPodTarget(config) {
  return withPodfile(config, (nextConfig) => {
    const marker = '    # @generated begin vouch-minimum-ios-pod-target';
    if (nextConfig.modResults.contents.includes(marker)) return nextConfig;

    const postInstallEnd = '  end\nend';
    const insertionIndex = nextConfig.modResults.contents.lastIndexOf(postInstallEnd);
    if (insertionIndex === -1) {
      throw new Error('[withAlarmKit] Unable to find the Podfile post_install block.');
    }

    const patch = `    # @generated begin vouch-minimum-ios-pod-target
    # Xcode 27 no longer builds Pods whose declared target is below iOS 15.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        deployment_target = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        next if deployment_target.nil? || Gem::Version.new(deployment_target) >= Gem::Version.new('15.0')

        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
    # @generated end vouch-minimum-ios-pod-target
`;

    nextConfig.modResults.contents =
      nextConfig.modResults.contents.slice(0, insertionIndex) +
      patch +
      nextConfig.modResults.contents.slice(insertionIndex);
    return nextConfig;
  });
}

function buildAppIntentsPackageSource() {
  return `// @generated by plugins/withAlarmKit.js
#if canImport(AppIntents) && canImport(VouchAlarmKit)
import AppIntents
import VouchAlarmKit

@available(iOS 26.0, *)
struct VouchAppIntentsPackage: AppIntentsPackage {
  static var includedPackages: [any AppIntentsPackage.Type] {
    [VouchAlarmKitAppIntentsPackage.self]
  }
}
#endif
`;
}

module.exports = function withAlarmKit(config) {
  config = withAlarmKitInfoPlist(config);
  config = withAlarmKitAppIntentsPackage(config);
  config = withMinimumIosPodTarget(config);
  return config;
};
