const { IOSConfig, withInfoPlist, withXcodeProject } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const APP_INTENTS_PACKAGE_FILE = 'VouchAlarmKitAppIntentsPackage.swift';

function withAlarmKitInfoPlist(config) {
  return withInfoPlist(config, (nextConfig) => {
    delete nextConfig.modResults.NSAlarmKitUsageDescription;
    return nextConfig;
  });
}

function withAlarmKitAppIntentsPackage(config) {
  return withXcodeProject(config, (nextConfig) => {
    const project = nextConfig.modResults;
    const projectRoot = nextConfig.modRequest.projectRoot;
    const projectName = nextConfig.modRequest.projectName;

    if (!projectName) {
      throw new Error('[withAlarmKit] Unable to resolve iOS project name.');
    }

    const sourceRoot = IOSConfig.Paths.getSourceRoot(projectRoot);
    const appIntentsPackagePath = path.join(sourceRoot, APP_INTENTS_PACKAGE_FILE);
    fs.writeFileSync(appIntentsPackagePath, buildAppIntentsPackageSource());

    const projectFilePath = `${projectName}/${APP_INTENTS_PACKAGE_FILE}`;
    if (!project.hasFile(projectFilePath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: projectFilePath,
        groupName: projectName,
        project,
      });
    }

    // Enable AppIntents metadata extraction from dependent static libraries
    const buildConfigs = project.pbxXCBuildConfigurationSection();
    for (const key in buildConfigs) {
      const config = buildConfigs[key];
      if (config.buildSettings && config.buildSettings.PRODUCT_NAME === projectName) {
        config.buildSettings.GENERATE_APPINTENTS_METADATA_FOR_DEPENDENCIES = 'YES';
      }
    }

    return nextConfig;
  });
}

function buildAppIntentsPackageSource() {
  return `// @generated by plugins/withAlarmKit.js
#if canImport(AppIntents) && canImport(VouchAlarmKit)
import AppIntents
import VouchAlarmKit

@available(iOS 26.0, *)
struct VouchAppIntentsPackage: AppIntentsPackage {
  static var includedPackages: [any AppIntentsPackage.Type] {
    [VouchAlarmKitAppIntentsPackage.self]
  }
}
#endif
`;
}

module.exports = function withAlarmKit(config) {
  config = withAlarmKitInfoPlist(config);
  config = withAlarmKitAppIntentsPackage(config);
  return config;
};
