import { StyleSheet } from 'react-native';
import { type Colors, radius, spacing, typography } from '@/lib/theme';

const makeStyles = (colors: Colors) => StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  body: {
    flex: 1,
    paddingHorizontal: spacing.md,
  },
  bodyContent: {
    gap: spacing.lg,
    paddingVertical: spacing.lg,
    paddingBottom: spacing.xxl,
  },

  // Account card
  accountContent: {
    gap: spacing.md,
  },
  accountIdentityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  accountIdentityMeta: {
    flex: 1,
    paddingTop: 2,
    gap: 4,
  },
  accountIdentityTitle: {
    fontSize: typography.base,
    color: colors.text,
    fontWeight: typography.semibold,
  },
  accountIdentitySub: {
    fontSize: typography.sm,
    color: colors.textMuted,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: typography.md,
    fontWeight: typography.bold,
    color: colors.text,
  },
  readOnlyField: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: colors.bg,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  readOnlyFieldText: {
    fontSize: typography.base,
    color: colors.text,
  },

  // Sections
  section: {
    gap: spacing.sm,
    paddingTop: spacing.lg,
  },
  sectionLabel: {
    fontSize: typography.base,
    fontWeight: typography.semibold,
    color: colors.textMuted,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  card: {},
  cardDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: spacing.sm,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  rowTinted: {
    borderWidth: 1,
    borderColor: '#7F1D1D66',
    backgroundColor: '#450A0A26',
    borderRadius: radius.md,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  rowDisabled: {
    opacity: 0.65,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
    minWidth: 0,
  },
  rowLabel: {
    fontSize: typography.base,
    color: colors.text,
    fontWeight: typography.normal,
    flexShrink: 1,
  },
  rowLabelDestructive: {
    color: colors.destructive,
  },
  trailingText: {
    fontSize: typography.sm,
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  defaultsContent: {
    gap: spacing.md,
  },
  defaultsField: {
    gap: spacing.sm,
  },
  friendSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.inputBg,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    minHeight: 46,
  },
  friendSearchInput: {
    flex: 1,
    color: colors.text,
    fontSize: typography.base,
    paddingVertical: 0,
  },
  defaultsLabel: {
    fontSize: typography.sm,
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  selectButton: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: colors.surface2,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectLabel: {
    color: colors.text,
    fontSize: typography.base,
    flex: 1,
    paddingRight: spacing.sm,
  },
  textInput: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: colors.bg,
    paddingHorizontal: spacing.md,
    color: colors.text,
    fontSize: typography.base,
  },
  usernameInlineField: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: colors.bg,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  usernameInlineLabel: {
    fontSize: typography.base,
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  usernameInlineInput: {
    flex: 1,
    minWidth: 0,
    color: colors.text,
    fontSize: typography.base,
    textAlign: 'right',
    paddingVertical: 0,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  toggleTextWrap: {
    flex: 1,
    gap: 2,
  },
  toggleTitle: {
    fontSize: typography.base,
    color: colors.text,
    fontWeight: typography.medium,
  },
  toggleSub: {
    fontSize: typography.sm,
    color: colors.textMuted,
    lineHeight: 18,
  },
  errorText: {
    fontSize: typography.sm,
    color: colors.destructive,
  },
  savingText: {
    fontSize: typography.sm,
    color: colors.textMuted,
  },
  successText: {
    fontSize: typography.sm,
    color: colors.success,
  },
  blockedUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.bg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  blockedUserMeta: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  blockedUserName: {
    fontSize: typography.base,
    color: colors.text,
    fontWeight: typography.medium,
  },
  blockedUserEmail: {
    fontSize: typography.sm,
    color: colors.textMuted,
  },
  unblockButton: {
    minHeight: 34,
    paddingHorizontal: spacing.md,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unblockButtonDisabled: {
    opacity: 0.6,
  },
  unblockButtonText: {
    fontSize: typography.sm,
    color: colors.text,
    fontWeight: typography.semibold,
  },
  friendsList: {
    gap: spacing.sm,
  },
  friendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.bg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  friendMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
  },
  friendAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  friendAvatarText: {
    color: colors.text,
    fontSize: typography.sm,
    fontWeight: typography.semibold,
  },
  friendText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  friendName: {
    fontSize: typography.base,
    color: colors.text,
    fontWeight: typography.medium,
  },
  friendEmail: {
    fontSize: typography.sm,
    color: colors.textMuted,
  },
  friendActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  friendIconActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  circleActionButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  friendButton: {
    minHeight: 34,
    paddingHorizontal: spacing.md,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  friendButtonDestructive: {
    borderColor: '#7F1D1D',
    backgroundColor: colors.destructiveMuted,
  },
  friendButtonDisabled: {
    opacity: 0.6,
  },
  friendButtonText: {
    fontSize: typography.sm,
    color: colors.text,
    fontWeight: typography.semibold,
  },
  friendButtonTextDestructive: {
    color: '#FCA5A5',
  },
  friendStateLabel: {
    fontSize: typography.sm,
    color: colors.textMuted,
    fontWeight: typography.medium,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  backdropTapTarget: {
    flex: 1,
  },
  pickerSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    borderTopWidth: 1,
    borderColor: colors.borderStrong,
    maxHeight: '62%',
    paddingBottom: spacing.md,
  },
  pickerHeader: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerTitle: {
    fontSize: typography.md,
    color: colors.text,
    fontWeight: typography.semibold,
  },
  pickerDone: {
    fontSize: typography.base,
    color: colors.text,
    fontWeight: typography.medium,
  },
  pickerRow: {
    paddingHorizontal: spacing.lg,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  pickerRowMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  pickerRowLabel: {
    fontSize: typography.base,
    color: colors.text,
  },
  pickerRowLabelDisabled: {
    color: colors.textSubtle,
  },
  previewButton: {
    minHeight: 32,
    paddingHorizontal: spacing.md,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewButtonText: {
    fontSize: typography.sm,
    color: colors.text,
    fontWeight: typography.medium,
  },
});

export { makeStyles };
